import { TreeTableHeaderObject } from './tree-table-header-object';
import { TreeTableRow } from './tree-table-row';
import { HttpClient } from '@angular/common/http';
import { TreeTableDataConfig, TreeTableDataServerConfig } from './tree-table-data-config';
export declare class TreeTableData {
    headers: TreeTableHeaderObject[];
    data: TreeTableRow[];
    isLoading: boolean;
    keyword: string;
    page: number;
    pageSize: number;
    lastParams: any;
    totalRowsCount: number;
    filteredRowsCount: number;
    splashMessageFlag: boolean;
    splashMessageContent: string;
    tokens: any[];
    isAllRowsExpanded: boolean;
    serverConfig: TreeTableDataServerConfig;
    config: TreeTableDataConfig;
    loadCounter: number;
    private http;
    constructor(config?: TreeTableDataConfig, serverConfig?: TreeTableDataServerConfig, http?: HttpClient);
    totalPagesCount(): number;
    getParams(): {};
    loadExcelData(callback?: any): void;
    loadData(callback?: any): void;
    allRowsExpanded(): boolean;
    allRowsCollapsed(): boolean;
    splashMessage(msg: string): void;
}
